config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  resources :products do
    member do
      get :purchase
    end
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
  end
  root 'items#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' 
  }
  devise_scope :user do
    get 'domiciles', to: 'users/registrations#new_domicile'
    post 'domiciles', to: 'users/registrations#create_domicile'
  end
  resources :users 
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    # @parents = Category.where(ancestry: nil)
    @products = Product.order("created_at DESC").limit(3)

    @parents = Category.all.order("id ASC").limit(13)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category.html.haml
.categories
  = link_to "#", class: "category__search" do
    カテゴリー
    %ul.category__parent.category__list
      - @parents.each do |parent| 
        %li
          = link_to "#", class: "category__parent--name" do
            = parent.name
          %ul.category__child.category__list
            - parent.children.each do |child|
              %li
                = link_to "#", class: "category__child--name" do
                  = child.name
                %ul.category__grandchild.category__list
                  - child.children.each do |grandchild|
                    %li
                      = link_to "#", class: " category__child--name" do
                        = grandchild.name 

app/views/items/index.html.haml
%header.pageheader
  .headercontents
    .mainheader
      .icon
        = link_to image_tag("material/logo/logo.png", class: "top-logo"), "#"
      .search-box
        %form.search-box__form{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
          %input{:name => "utf-8", :type => "hidden", :value => ""}/
          %input{:name => "key", :placeholder => "キーワードから探す"}/
          %button.search-box__form--button{:type => "submit"}
            .search-icon
              = image_tag("material/icon/icon-search 1.png", class: "search-img")

    .navigator
      %ul.left-lists         
        //カテゴリーリスト(宮嶋) 
        = render partial: "items/category"
        %li.left-lists--right
          = link_to 'ブランド','#',class:'btn'
      %ul.right-lists
      - if user_signed_in?
        %li.right-lists--left
          = link_to 'マイページ', user_path(current_user.id), class:'btn'
        %li.right-lists--right
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'btn'
      - else
        %li.right-lists--left
          = link_to 'ログイン', new_user_session_path,class:'btn'
        %li.right-lists--right
          = link_to '新規登録', new_user_registration_path, class:'btn'


.mainwrapper
  %section.topmainvisual
    .contents
      .content__title
        %br/
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAは誰でも簡単に出品・購入できる
        %br/
        フリマアプリです
      .content__btn
        .content__btn--appstore
          = link_to image_tag("material/logo/download-on-the-app-store-apple-2.svg", class: "appstore"), "#"
        .content__btn--googleplay
          = link_to image_tag("material/logo/google-play-badge.svg", class: "googleplay"), "#"

  %section.topintroduction
    .subtitle
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__photo
          = image_tag("material/pict/pict-reason-01.jpg", class: "reasonimage")
          .list__number
            1
        .list__title
          %span
            3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！

      %li.list
        .list__photo
          = image_tag("material/pict/pict-reason-02.jpg", class: "reasonimage")
          .list__number
            2
        .list__title
          %span
            シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        .list__photo
          = image_tag("material/pict/pict-reason-03.jpg", class: "reasonimage")
          .list__number
            3
        .list__title
          手数料
          %span
            業界最安
        .list__description
          最大3%でお得に出品&購入！

  %section.topmiddleapp
    .middle-container
      .middle-container__title
        会員数日本1位
      %p.middle-container__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .content__btn
        .content__btn--appstore
          = link_to image_tag("material/logo/download-on-the-app-store-apple-2.svg", class: "appstore"), "#"
        .content__btn--googleplay
          = link_to image_tag("material/logo/google-play-badge.svg", class: "googleplay"), "#"

  %section.topfeature
    .features
      FURIMAの特徴
    %ul.feature-lists
      %li.feature-list
        .feature-list__photo
          = image_tag("material/icon/icon-01.png", class: "featureimage")
        .feature-list__title
          簡単に売り買いできる
        %p.feature-list__description
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.feature-list
        .feature-list__photo
          = image_tag("material/icon/icon-03.png", class: "featureimage")
        .feature-list__title
          売上金は翌年振込みに対応
        %p.feature-list__description
          午前9時までに振込を依頼いただければ、翌年に指定の口座に入金いたします!
      %li.feature-list
        .feature-list__photo
          = image_tag("material/icon/icon-04.png", class: "featureimage")
        .feature-list__title
          様々な支払いに対応
        %p.feature-list__description
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.pickupcontainer
    .pickup-title
      ピックアップカテゴリー
    .pickup-title-right
      %i.fas.fa-chevron-right
      = link_to ("もっと見る"),products_path
    .pickup-products
      .pickup-products__head
        = link_to "新規投稿商品", '#', class: "pickup-link"
      .pickup-lists
        - @products.each do |product|
          -if (product.buyer_id)
            .pickup-list
              = link_to product_path(product.id), class: "productdetail-link" do
                .pickup-list__photo
                  = image_tag product.product_images[0].src.url, class:'pickupproduct-image'
                  -if product.buyer_id.present?
                    .pickup-lists__sold
                      .pickup-lists__sold__inner SOLD
                .pickup-list__text
                  .product-name
                    = product.name
                  .product-details
                    %ul
                      %li.price
                        = product.pricing
                      %li.like
                        ★0
                    .tax
                      （税込）
          - else   
            .pickup-list
              = link_to product_path(product.id), class: "productdetail-link" do
                .pickup-list__photo
                  = image_tag product.product_images[0].src.url, class:'pickupproduct-image'
                .pickup-list__text
                  .product-name
                    = product.name
                  .product-details
                    %ul
                      %li.price
                        = product.pricing
                      %li.like
                        ★0
                    .tax
                      （税込）
  %section.pickupcontainer
    .pickup-title
      ピックアップブランド
    .pickup-products
      .pickup-products__head
        = link_to "アーカイバ", '/', class: "pickup-link"
      .pickup-lists
        .pickup-list
          = link_to "/", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/medical_mask_urethane.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）
        .pickup-list
          = link_to "/", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/pleats_mask_hida.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）
        .pickup-list
          = link_to "#", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/butoukai_kamen.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク？
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）
        .pickup-list
          = link_to "#", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/medical_mask_n95.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）

%aside.bottum-app
  .bottum-content
    .headlines
      .headlines__title
        だれでもかんたん、人生を変えるフリマアプリ
      .headlines__text
        今すぐ無料ダウンロード！
      .content__btn
        .content__btn--appstore
          = link_to image_tag("material/logo/download-on-the-app-store-apple-2.svg", class: "appstore"), "#"
        .content__btn--googleplay
          = link_to image_tag("material/logo/google-play-badge.svg", class: "googleplay"), "#"

.footer
  %ul.contents
    %li.content
      .content__top
        FURIMAについて
      %ul.content__lists
        %li.content__lists--list
          = link_to "会社概要（運営会社）","#", class: "footer-link"
        %li.content__lists--list
          = link_to "プライバシーポリシー","#", class: "footer-link"
        %li.content__lists--list
          = link_to "FURIMA利用規約","#", class: "footer-link"
        %li.content__lists--list
          = link_to "ポイントに関する特約","#", class: "footer-link"
    %li.content
      .content__top
        FURIMAを見る
      %ul.content__lists
        %li.content__lists--list
          = link_to "カテゴリー一覧","#", class: "footer-link"
        %li.content__lists--list
          = link_to "ブランド一覧","#", class: "footer-link"
    %li.content
      .content__top
        ヘルプ＆ガイド
      %ul.content__lists
        %li.content__lists--list
          = link_to "FURIMAガイド","#", class: "footer-link"
        %li.content__lists--list
          = link_to "FURIMAロゴ利用ガイドライン","#", class: "footer-link"
        %li.content__lists--list
          = link_to "お知らせ","#", class: "footer-link"
  .footer__logo
    = link_to image_tag("material/logo/logo-white.png", class: "footer-logo"), "#"
  .footer__logotext
    © FURIMA

= link_to new_product_path, class: "exhibitionBtn-link" do
  .exhibitionBtn
    %span.exhibitionBtn__text
      出品する
    = image_tag("material/icon/icon_camera.png", class: "exhibitionBtn__icon")

app/views/items/show.html.haml
.main
  .showMain
    .contentLeft
    .showMain__contentRight
      .topContent
        .topContent__itemBox
          %h2.itemBox__name product2
          .topContent__itemBox__body
            %ul
              %li
                = link_to image_tag("material/logo/logo.png", width: '375'), '#'
                %ul
                  %li
                    = link_to image_tag("material/logo/logo.png", width: '75',height: '75'), '#'
                  %li
                    = link_to image_tag("material/logo/logo.png", width: '75',height: '75'), '#'
                  %li
                    = link_to image_tag("material/logo/logo.png", width: '75',height: '75'), '#'
          .topContent__itemBox__price
            %span
              ¥20000
            .topContent__itemBox__price__detail
              %span
                (税込)
              %span
                送料込み
            = link_to ("購入画面に進む"),'#',class: "PurchaseBtn"
          .itemDetail 親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れぬ。別段深い理由でもない。新築の二階から首を出していたら、同級生の一人が冗談に、いくら威張っても、そこから飛び降りる事は出来まい。弱虫やーい。と囃したからである。小使に負ぶさって帰って来た時、おやじが大きな眼をして二階ぐらいから飛び降りて腰
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td hoge
                %tr
                  %th カテゴリー
                  %td
                    = link_to ("メンズ"),'#'
                    %br/
                    = link_to ("ジャケット/アウター"),'#'
                    %br/
                    = link_to ("ノーカラージャケット"),'#'
                %tr
                  %th 商品の状態
                  %td 新品/未使用
                %tr
                  %th 配送料の負担
                  %td 着払い（購入者負担）
                %tr
                  %th 発送元の地域
                  %td
                    = link_to ("青森県"),'#'  
                %tr
                  %th 発送日の目安
                  %td 1-2日で発送
          .optionalArea
            %ul
              %li#likeBtn.optionalBtn.likeBtn
                = icon("fas", "book")
                お気に入り 0
            %ul.optional
              %li.optionalBtn
                = link_to ("不適切な商品の通報"),'#'
        .commentBox
          %ul.commentContents
          %form#new_comment.new_comment{"accept-charset" => "UTF-8", :action => "#", :method => "post"}
            %input{:name => "utf8", :type => "hidden", :value => "✓"}/
            %input{:name => "authenticity_token", :type => "hidden", :value => "yp/QcQnE9PRzexqN3LPb7drKH2IdB6YiaPFBEvlw/ljgtAacLtRrjhRvw1d3C27HPf+Q0DGqMLafQH9ZpYVopA=="}/
            %textarea#comment_body{:name => "comment[body]", :required => "required"}
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br/
            %button.commentBtn{:name => "button", :type => "submit"}
              コメントする
      %ul.links
        %li
          %i.fas.fa-chevron-left
          = link_to ("前の商品"),'#'
        %li
          = link_to ("後ろの商品"),'#'
          %i.fas.fa-chevron-right
      .relatedItems
        = link_to ("メンズをもっと見る"),'#'
        .productLis