config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  resources :products do
    member do
      get :purchase
    end
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
  end
  root 'items#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' 
  }
  devise_scope :user do
    get 'domiciles', to: 'users/registrations#new_domicile'
    post 'domiciles', to: 'users/registrations#create_domicile'
  end
  resources :users 
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp" 
  before_action :set_card, only: [:show, :destroy]

  def new
    @card = Card.where(user_id: current_user.id)
    redirect_to card_path(@card.first.id) if @card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    
    if params["payjp_token"].blank?
       redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
         email: current_user.email,
         card: params["payjp_token"],
         metadata: {user_id: current_user.id} 
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
      else
        redirect_to action: "create"
      end
    end
  end

  def show
    # @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
    end
    ## 有効期限'月'を定義
    # @exp_month = @customer_card.exp_month.to_s
    ## 有効期限'年'を定義
    # @exp_year = @customer_card.exp_year.to_s.slice(2,3)
  end

  def destroy
    # @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      @card.destroy
      redirect_to card_path
      # 前前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
      # Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      # customer = Payjp::Customer.retrieve(@card.customer_id)
      # customer.delete
      # # destroy!
      # if @card.destroy
      
      # else
      #   redirect_to card_path(current_user.id), alert: "削除できませんでした。"
      # end
    end
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards.html.haml
= form_with url:cards_path, method: :post, html: { name: "inputForm" },class:"form" ,id:"charge-form" do |f|
  .credit-card-head
    クレジットカード情報入力
  .credit-card-body
    .credit-card-body__form-group
      .credit-card-body__form-group__top
        .credit-card-body__form-group__top__card-no
          カード番号
        .credit-card-body__form-group__top__required
          必須
      %input.credit-card-body__form-group__input{ type: 'text', id: "payment_card_no", placeholder: '半角数字のみ', maxlength: '19' }
      %ul.credit-card-body__form-group__list
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/visa.svg?2246739708', width: '49', height: '20' 
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/master-card.svg?2246739708', width: '34', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/saison-card.svg?2246739708', width: '30', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/jcb.svg?2246739708', width: '32', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/american_express.svg?2246739708', width: '21', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?2246739708', width: '32', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/discover.svg?2246739708', width: '32', height: '20'
    .credit-card-body__form-group__expire
      .credit-card-body__form-group__expire__top
        .credit-card-body__form-group__expire__top__expiration-date
          有効期限
        .credit-card-body__form-group__expire__top__required
          必須
      .credit-card-body__form-group__expire__deta
        .credit-card-body__form-group__expire__half
          = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'form-signup__month__select', id:'payment_card_month'
          %span.month-year 月
        .credit-card-body__form-group__expire__year
          = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'form-signup__month__select', id:'payment_card_year'
          %span.month-year 年
    .credit-card-body__form-group__sekyuriti
      .credit-card-body__form-group__sekyuriti__top
        .credit-card-body__form-group__sekyuriti__top__code
          セキュリティコード
        .credit-card-body__form-group__sekyuriti__top__required
          必須
      %input.credit-card-body__form-group__sekyuriti__form{ type: 'text', id: 'payment_card_cvc', placeholder: 'カード背面4桁もしくは3桁の番号' }
      .credit-card-body__form-group__sekyuriti__text
        カード裏面の番号とは？
    .credit-card-body__form-group__card-token
      = submit_tag "登録する" ,id: "payment_card_submit-button", class: "top__margin"

app/views/cards/_credit-cards.html.haml
= form_with url:cards_path, method: :post, html: { name: "inputForm" },class:"form" do |f|
  .credit-card-head
    クレジットカード情報入力
  .credit-card-body
    .credit-card-body__form-group
      .credit-card-body__form-group__top
        .credit-card-body__form-group__top__card-no
          カード番号
        .credit-card-body__form-group__top__required
          必須
      %input.credit-card-body__form-group__input{ type: 'text', placeholder: '半角数字のみ', maxlength: '19' }
      %ul.credit-card-body__form-group__list
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/visa.svg?2246739708', width: '49', height: '20' 
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/master-card.svg?2246739708', width: '34', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/saison-card.svg?2246739708', width: '30', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/jcb.svg?2246739708', width: '32', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/american_express.svg?2246739708', width: '21', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?2246739708', width: '32', height: '20'
        %li
          = image_tag '//pcweb-assets.mercdn.net/assets/img/card/discover.svg?2246739708', width: '32', height: '20'
    .credit-card-body__form-group__expire
      .credit-card-body__form-group__expire__top
        .credit-card-body__form-group__expire__top__expiration-date
          有効期限
        .credit-card-body__form-group__expire__top__required
          必須
      .credit-card-body__form-group__expire__deta
        .credit-card-body__form-group__expire__half
          = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'form-signup__month__select', id:'exp_month'
          %span.month-year 月
        .credit-card-body__form-group__expire__year
          = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'form-signup__month__select', id:'exp_year'
          %span.month-year 年
    .credit-card-body__form-group__sekyuriti
      .credit-card-body__form-group__sekyuriti__top
        .credit-card-body__form-group__sekyuriti__top__code
          セキュリティコード
        .credit-card-body__form-group__sekyuriti__top__required
          必須
      %input.credit-card-body__form-group__sekyuriti__form{ type: 'text', id: 'cvc', placeholder: 'カード背面4桁もしくは3桁の番号' }
      .credit-card-body__form-group__sekyuriti__text
        カード裏面の番号とは？
    .credit-card-body__form-group__card-token
      = submit_tag "登録する" ,id: "token_submit", class: "top__margin"

app/views/cards/_side-credit-cards.html.haml
.mypage__left
  .mypage__left__top
    .mypage__left__list
      %ls
      =link_to "トップページ", root_path, class: 'mypage-left-log' 
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "お知らせ", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "やることリスト", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "いいね！一覧", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "出品する", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "下書き一覧", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "出品した商品-出品中", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "出品した商品-取引中", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "出品した商品-売却済", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "出品した商品-取引中", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "出品した商品-過去の取引", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "ニュース一覧", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "評価一覧", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "ガイド", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__menu
    .mypage__left__list
      %ls
      =link_to "お問い合わせ", "#", class: 'mypage-left-log'
    .mypage__left__menu__right-log
      %i.fas.fa-chevron-right 


  .mypage__left__nav-head
    フリペイ
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "売上げ・振り込み申請", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "ポイント", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  
  .mypage__left__nav-head
    設定
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "プロフィール", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "発送元・お届け先住所変更", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "支払い方法", new_card_path, class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "メール/パスワード", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "本人情報", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "電話番号の確認", "#", class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 
  .mypage__left__pey
    .mypage__left__pey-item
      %ls
      =link_to "ログアウト", "destroy_user_session_path", method: :delete, class: 'mypage-left-log'
    .mypage__left__pey__right-log
      %i.fas.fa-chevron-right 

app/views/cards/create.html.haml
.create
  .create__header_blank
  .create__frame
    .create__frame__message
      登録が完了しました
    .create__frame__box
      .create__frame__box__left
        = link_to "マイページに戻る", "/users/#{current_user.id}", class: "my_page_link__btn"
        -# = link_to "マイページに戻る", "/", class: "my_page_link__btn"

app/views/cards/destroy.html.haml
.destroy
  .destroy__header_blank
  .destroy__frame
    .destroy__frame__message
      削除が完了しました
    .destroy__frame__box
      .destroy__frame__box__left
        = link_to "クレジットカード新規登録", new_card_path , class: "credit_card_new_link__btn"
        -# = link_to "クレジットカード新規登録", '#' , class: "credit_card_new_link__btn"
      .destroy__frame__box__right
        = link_to "トップページに戻る", root_path(current_user.id), class: "my_page_link__btn"
        -# = link_to "トップページに戻る", '/', class: "my_page_link__btn"

app/views/cards/new.html.haml
.wrapper
  = render "side-credit-cards"
  = render "cards"

app/views/cards/show.html.haml
.show
  .show__header_blank
  .show__frame
    .show__frame__title
      登録クレジットカード情報
    .show__frame__list
      .show__frame__list__title
        クレジットカード一覧
      .show__frame__list__info
        .show__frame__list__info__box
          .show__frame__list__info__box__left
            .card_brand
              -# 画像
              -# = image_tag "cards/#{@card_src}", class: "credit_card_info__brand__img", alt: @card_brand
          .show__frame__list__info__box__right    
            .card_numbers
              .number
                -# **** **** ****
                = "**** **** **** " + @customer_card.last4
              -# .expiration_date
              -#   .expiration_date__title
              -#     有効期限
              -#   .expiration_date__info
              -#     = "#{@exp_month}  /  #{@exp_year}"
        .destroy__function
          .destroy__function__link
            - card = Card.find_by(user_id: current_user.id)
            = link_to "削除する", card_path, method: :delete, class: "destroy__function__btn" 
            -# =link_to "削除する", '#', class: "destroy__function__btn" 
    .show__frame__footer
      = link_to "トップページに戻る", "/", class: "back_top_btn"