config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  resources :products do
    member do
      get :purchase
    end
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    
  end
  root 'items#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' 
  }
  devise_scope :user do
    get 'domiciles', to: 'users/registrations#new_domicile'
    post 'domiciles', to: 'users/registrations#create_domicile'
  end
  resources :users 
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id",optional: true
  #意味：userテーブルをseller/buyerに変更、カラム名はseller_id・buyer_idで外部キーだよ
  #optional: true＝今は購入者は関係ないのでNULLデータでもDBに入る様設定している。これがないとデータがないと判断しDBに商品のレコードが残らない。
  

  # active-hash勢アソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :postage
  belongs_to_active_hash :preparation_day
  # 上記大野商品出品機能のため追記

  
  validates_associated :product_images
  # バリデーション
  validates :name, presence: true, length: {maximum: 40}
  validates :description, presence: true, length: {maximum: 1000}
  validates :prefecture, presence: true
  validates :condition, presence: true
  validates :postage, presence: true
  validates :preparation_day, presence: true
  validates :pricing, presence: true, numericality: { only_integer: true, greater_than: 300, less_than: 10000000}
  validates :product_images, presence: true

 
  # has_many :comments, dependent: :destroy
  # has_many :users, through: :comments
  # has_many :favorites, dependent: :destroy
  # has_many :users, through: :favorites
  
  # カテゴリーと紐付け(宮嶋)
  belongs_to :category, dependent: :destroy
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images, allow_destroy: true
  # ↑１行追記(みやじ、product.scss new.html, product_image)
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # ログインしてないとindexとshow以外はアクセス不可。出品・編集などができない様にするusers.rbにも記載したので見て
  before_action :set_product, only: [:edit, :update, :destroy]
  # set_productメソッド（@product = Product.find(params[:id])は編集・更新・削除のみで働く

  def index
    @products = Product.all.order(created_at: :desc)
    @images = ProductImage.all
  end
  
  def show
    
    @products = Product.find(params[:id])
    @prefecture = Prefecture.find(@products.prefecture_id)
    @condition = Condition.find(@products.condition_id)
    @preparationday = PreparationDay.find(@products.preparation_day_id)
    #category表示(宮嶋)
    @category = @products.category
   
    @user = User.find(@products.seller_id)
  end

  def purchase
    @products = Product.find(params[:id])
    @address = Domicile.find_by(user_id: current_user.id)
  end

  # 商品出品
  def new
    @product = Product.new
    @product.product_images.new
    #セレクトボックスの初期値設定(宮嶋)
    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def create

    @product = Product.new(product_params)
    @product.seller_id = current_user.id
    if @product.save
      redirect_to root_path
    else
      @product.product_images.new
      render :new
    end
  end

  #親カテゴリーが選択された後のアクション(宮嶋)
  def get_category_children  
    @category_children = Category.find_by(id: "#{params[:parent_id]}").children
  end
  
  def get_category_grandchildren    
    @category_grandchildren = Category.find("#{params[:child_id]}").children    
  end



  def edit
    if @product.seller_id != current_user.id  #出品者が現ログインユーザでないと編集できない様に
      #セレクトボックスの初期値設定(宮嶋)
      @category_parent_array = ["選択してください"]
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
        redirect_to root_path

      grandchild_category = @product.category_child
      child_category = grandchild_category.parent
      
      @category_children_array = Category.where(ancestry: child_category.ancestry)
      @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
      end
    end  
  end


  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path  #商品一覧画面へ移動
    else
      render :show  #商品詳細画面でやり直し
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :condition_id,:category_id, :postage_id, :prefecture_id, :preparation_day_id, :pricing, product_images_attributes: [:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_form.html.haml
.exhibition__page
  .exhibition__page__header
    = link_to image_tag('material/logo/logo.png', class: "logo"), "/"
  .exhibition__page__box
    = form_for @product do |f|
      .exhibition__page__box__in
        = render 'layouts/error_messages', model: f.object
        %h1
          出品画像
          %span 必須
        %br 最大10枚までアップロードできます
        #image-box
          #previews
            - if @product.persisted?
              - @product.product_images.each_with_index do |image, i|
                = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
          = f.fields_for :product_images do |image|
            .js-file_group{"data-index" => image.index}
              = image.file_field :src, class: 'js-file'
              %br/
              .js-remove 削除
            - if @product.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
          - if @product.persisted?
            .js-file_group{"data-index" => @product.product_images.count}
              = file_field_tag :src, name: "product[product_images_attributes][#{@product.product_images.count}][src]", class: 'js-file'
              .js-remove 削除
        %h1
          商品名
          %span 必須
        .form
          =f.text_field :name, placeholder: "40文字まで"
          - if @product.errors.include?(:name)
            %p= @product.errors.full_messages_for(:name).first
        %h1
          商品の説明
          %span 必須
        .form
          =f.text_area :description, size: "78%x7", placeholder: "商品の説明 (必須,1,000文字以内)                                                                              (色、素材、重さ、定価、注意点など)                                                                                        例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。"
          - if @product.errors.include?(:description)
            %p= @product.errors.full_messages_for(:description).first
        %h2
          商品の詳細
        %h1
        カテゴリー
        %span 必須
        .form__category__select
          = f.collection_select :category_id, Category.roots, :id, :name, {prompt: "選択してください",selected: @product.category&.root_id}, {class: 'category__select', id: 'parent_category'}
         
          
          - if @product.errors.include?(:category)
            %p= @product.errors.full_messages_for(:category).first


        -# %h1
        -# ブランド(任意)
        -# .form
        -#   =f.text_field :bland
        %h1
          商品状態
          %span 必須
        .form
          =f.collection_select :condition_id, Condition.all, :id, :name, {prompt:"選択してください"}, {class:""}
          -# - if @product.errors.include?(:condition)
          -#   %p= @product.errors.full_messages_for(:condition).first
        %h2
          配送について
        %h1
          配送料の負担
          %span 必須
        .form
          =f.collection_select :postage_id, Postage.all, :id, :name, {prompt:"選択してください"}, {class:""}
          - if @product.errors.include?(:postage)
            %p= @product.errors.full_messages_for(:postage).first
        %h1
          発送元の地域
          %span 必須
        .form
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"}, {class:""}
          - if @product.errors.include?(:prefecture)
            %p= @product.errors.full_messages_for(:prefecture).first
          
        %h1
          発送までの日数
          %span 必須
        .form
          =f.collection_select :preparation_day_id, PreparationDay.all, :id, :name, {prompt:"選択してください"}, {class:""}
          - if @product.errors.include?(:preparation_day)
            %p= @product.errors.full_messages_for(:preparation_day).first
        %h2
          価格(¥300~9,999,999)  
        %h1
          販売価格
          %span 必須
        .form
          =icon('fas','yen-sign')
          =f.text_field :pricing, class: ""
          - if @product.errors.include?(:pricing)
            %p= @product.errors.full_messages_for(:pricing).first
        .action
          =f.submit "出品する"
  .newFooter
    .footercontents
      %ul.footerlists
        %li.footerlists__list
          = link_to "プライバシーポリシー","#", class: "footer-link"
        %li.footerlists__list
          = link_to "FURIMA利用規約","#", class: "footer-link"
        %li.footerlists__list
          = link_to "特定商取引に関する表記","#", class: "footer-link"
    .footerLogo
      = link_to image_tag("material/logo/logo-white.png", class: "footer-logo"), root_path
    .footerLogo-text
      © FURIMA

app/views/products/index.html.haml
%header.pageheader
  .headercontents
    .mainheader
      .icon
        = link_to image_tag("material/logo/logo.png", class: "top-logo"), "/"
      .search-box
        %form.search-box__form{"accept-charset" => "UTF-8", action: "#", method: "get"}
          %input{name: "utf-8", type: "hidden", value: ""}/
          %input{name: "key", placeholder: "キーワードから探す"}/
          %button.search-box__form--button{type: "submit"}
            .search-icon
              = image_tag("material/icon/icon-search 1.png", class: "search-img")
    .navigator
      %ul.left-lists
        %li.left-lists--left
          = link_to 'カテゴリー','#',class:'btn'
        %li.left-lists--right
          = link_to 'ブランド','#',class:'btn'
      %ul.right-lists
      - if user_signed_in?
        %li.right-lists--right
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'btn'
      - else
        %li.right-lists--left
          = link_to 'ログイン', new_user_session_path,class:'btn'
        %li.right-lists--right
          = link_to '新規登録', new_user_registration_path, class:'btn'

.mainwrapper
  %section.pickupcontainer
    .pickup-title
      ピックアップカテゴリー
    .pickup-products
      .pickup-products__head
        = link_to "新規投稿商品", '/', class: "pickup-link"
      .pickup-lists
        - @products.each do |product|
          -if (product.buyer_id)
            .pickup-list
              = link_to product_path(product.id), class: "productdetail-link" do
                .pickup-list__photo
                  = image_tag product.product_images[0].src.url, class:'pickupproduct-image'
                  -if product.buyer_id.present?
                    .pickup-lists__sold
                      .pickup-lists__sold__inner SOLD
                .pickup-list__text
                  .product-name
                    = product.name
                  .product-details
                    %ul
                      %li.price
                        = product.pricing
                      %li.like
                        ★0
                    .tax
                      （税込）
          - else   
            .pickup-list
              = link_to product_path(product.id), class: "productdetail-link" do
                .pickup-list__photo
                  = image_tag product.product_images[0].src.url, class:'pickupproduct-image'
                .pickup-list__text
                  .product-name
                    = product.name
                  .product-details
                    %ul
                      %li.price
                        = product.pricing
                      %li.like
                        ★0
                    .tax
                      （税込）
  %section.pickupcontainer
    .pickup-title
      ピックアップブランド
    .pickup-products
      .pickup-products__head
        = link_to "アーカイバ", '/', class: "pickup-link"
      .pickup-lists
        .pickup-list
          = link_to "/", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/medical_mask_urethane.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）
        .pickup-list
          = link_to "/", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/pleats_mask_hida.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）
        .pickup-list
          = link_to "#", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/butoukai_kamen.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク？
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）
        .pickup-list
          = link_to "#", class: "productdetail-link" do
            .pickup-list__photo
              = image_tag("material/products/medical_mask_n95.png", class: "pickupproduct-image")
            .pickup-list__text
              .product-name
                マスク
              .product-details
                %ul
                  %li.price
                    1000円
                  %li.like
                    ★0
                .tax
                  （税込）

%aside.bottum-app
  .bottum-content
    .headlines
      .headlines__title
        だれでもかんたん、人生を変えるフリマアプリ
      .headlines__text
        今すぐ無料ダウンロード！
      .content__btn
        .content__btn--appstore
          = link_to image_tag("material/logo/download-on-the-app-store-apple-2.svg", class: "appstore"), "#"
        .content__btn--googleplay
          = link_to image_tag("material/logo/google-play-badge.svg", class: "googleplay"), "#"

.footer
  %ul.contents
    %li.content
      .content__top
        FURIMAについて
      %ul.content__lists
        %li.content__lists--list
          = link_to "会社概要（運営会社）","#", class: "footer-link"
        %li.content__lists--list
          = link_to "プライバシーポリシー","#", class: "footer-link"
        %li.content__lists--list
          = link_to "FURIMA利用規約","#", class: "footer-link"
        %li.content__lists--list
          = link_to "ポイントに関する特約","#", class: "footer-link"
    %li.content
      .content__top
        FURIMAを見る
      %ul.content__lists
        %li.content__lists--list
          = link_to "カテゴリー一覧","#", class: "footer-link"
        %li.content__lists--list
          = link_to "ブランド一覧","#", class: "footer-link"
    %li.content
      .content__top
        ヘルプ＆ガイド
      %ul.content__lists
        %li.content__lists--list
          = link_to "FURIMAガイド","#", class: "footer-link"
        %li.content__lists--list
          = link_to "FURIMAロゴ利用ガイドライン","#", class: "footer-link"
        %li.content__lists--list
          = link_to "お知らせ","#", class: "footer-link"
  .footer__logo
    = link_to image_tag("material/logo/logo-white.png", class: "footer-logo"), "#"
  .footer__logotext
    © FURIMA

app/views/products/new.html.haml
= render partial: "products/product_form"

app/views/products/purchase.html.haml
.main
  .header
    = link_to image_tag('material/logo/logo.png', class: "logo"), "/"
  .main__box

    %section.main__box__title
      購入確認情報
    %section.Product-information
      .Product-information-box
        .image
          = image_tag @products.product_images[0].src.url, class:'pickupproduct-image'
        .comment
          %p.com
            = @products.name
          %p.com2
            = @products.pricing
            （税込) 送料込み
    %section.payment
      .payment-box
        .cSGTly
          %span 支払い金額
          %span.jYZlcv 
            ¥
            = @products.pricing
        .jReTKH
          %label{:for => "point-checkbox-id"}
            %span.kRgxCd
              ポイントを使用（所持ポイント: P0）
    %section.payment-methods
      .comment
        .comment1
          %h3 支払い方法
        %a.hJNIGG{:href => "/cards/new"}
          %svg{"aria-hidden" => "true", :fill => "#0095ee", "fill-rule" => "evenodd", :height => "16", :viewbox => "0 0 24 24", :width => "16"}
            %path{:d => "M17.51,11.3H12.7v-5a.7.7,0,0,0-1.4,0v5h-5a.7.7,0,0,0,0,1.4h5v4.81a.7.7,0,0,0,1.4,0V12.7h4.81a.7.7,0,0,0,0-1.4Z"}
            %path{:d => "M12,2A10,10,0,1,0,22,12,10,10,0,0,0,12,2Zm0,18.6A8.6,8.6,0,1,1,20.6,12,8.61,8.61,0,0,1,12,20.6Z"}
          %span 登録してください
    %section.Shipping
      .box
        .dVXrhZ
          %h3 配送先
          %a.sc-SFOxd.dZdLmH{:href => "/users/:id/edit"} 変更する
        .comment
          %p 
          = "〒 " + "#{@address.postal_code}"
          %p
          = @address.prefecture_id
          %p  
          = @address.city
          %p
          = @address.firstname
          = @address.lastname  
    %section.comment
      .comment1
        .comment2 
          - if (current_user.card)
            .comment3
              =link_to "購入する", buy_product_purchases_path(@products.id), method: :GET
          - else 
            決済方法を登録してください  
  #footer
    .footer-box
      %ul
        %li
          %a{:href => "/jp/privacy/"} プライバシーポリシー
        %li
          %a{:href => "/jp/tos/"} 利用規約
        %li
          %a{:href => "/jp/tokutei/"} 特定商取引に関する表記
    %a
      = image_tag ('material/logo/logo.png'), class: "logo"

app/views/products/show.html.haml
%header.pageheader
  .headercontents
    .mainheader
      .icon
        = link_to image_tag("material/logo/logo.png", class: "top-logo"), "/"
      .search-box
        %form.search-box__form{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
          %input{:name => "utf-8", :type => "hidden", :value => ""}/
          %input{:name => "key", :placeholder => "キーワードから探す"}/
          %button.search-box__form--button{:type => "submit"}
            .search-icon
              = image_tag("material/icon/icon-search 1.png", class: "search-img")

    .navigator
      %ul.left-lists
        %li.left-lists--left
          = link_to 'カテゴリー','#',class:'btn'
        %li.left-lists--right
          = link_to 'ブランド','#',class:'btn'
      %ul.right-lists
      - if user_signed_in?
        %li.right-lists--left
          = link_to 'マイページ', user_path(current_user.id), class:'btn'
        %li.right-lists--right
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'btn'
      - else
        %li.right-lists--left
          = link_to 'ログイン', new_user_session_path,class:'btn'
        %li.right-lists--right
          = link_to '新規登録', new_user_registration_path, class:'btn'

.main-show
  .showMain
    .contentLeft
    .showMain__contentRight
      .topContent
        .topContent__itemBox
          %h2.itemBox__name
            = @products.name
          .topContent__itemBox__body
            = image_tag @products.product_images[0].src.url, class:'item-image'
            -if @products.buyer_id.present? 
              .topContent__itemBox__body__sold
                .topContent__itemBox__body__sold__inner SOLD
          .main-content__photoSub
            - @products.product_images.each do |photo|
              = image_tag photo.src.url, class:'main-content__photoSub--small'
      
          .topContent__itemBox__price
            %span
              ¥
              = @products.pricing 
              %span
                円
            .topContent__itemBox__price__detail
              %span
                (税込)
              %span
                送料込み
          .topContent__itemBox__purchaseBtn
            -if (user_signed_in? && @products.buyer_id == nil)
              -if (current_user.id == @products.seller_id)
                %button.btn
                  = link_to "商品情報を編集",edit_product_path, id: "edit-btn"
                %button.btn
                  = link_to '削除',product_path, method: :delete, data: {confirm: "削除しますか？"}
              - else
                %button.btn
                  = link_to "購入に進む" ,purchase_product_path(@products.id), method: :get  
                    
          .itemDetail
            = @products.description
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @user.nickname
                %tr
                  %th カテゴリー
                  %td.category
                    //ルートカテゴリーだけ
                    -if @category.depth == 0 
                      = link_to "#{@category.name}", "#", class: "rootname"
                      //ルート、親だけ  
                    - elsif @category.depth == 1 #parent
                      = link_to "#{@category.parent.name}" , "#", class: "rootname"
                      = link_to "#{@category.name}", "#", class: "parentname"
                      //ルート、親、子まで  
                    - elsif @category.depth == 2 # child
                      = link_to "#{@category.root.name}", "#", class: "rootname"
                      = link_to "#{@category.parent.name}", "#", class: "parentname"
                      = link_to "#{@category.name}", "#", class: "childname"

                %tr
                  %th 商品の状態
                  %td
                    = @condition.name
                %tr
                  %th 配送料の負担
                  %td 着払い（購入者負担）
                %tr
                  %th 発送元の地域
                  %td.color
                    = @prefecture.name
                %tr
                  %th 発送日の目安
                  %td
                    = @preparationday.name
          .optionalArea
            %ul
              %li#likeBtn.optionalBtn.likeBtn
                = icon("fas", "book")
                お気に入り 0
            %ul.optional
              %li.optionalBtn
                = link_to ("不適切な商品の通報"),'#'
        .commentBox
          %ul.commentContents
          %form#new_comment.new_comment{"accept-charset" => "UTF-8", :action => "#", :method => "post"}
            %input{:name => "utf8", :type => "hidden", :value => "✓"}/
            %input{:name => "authenticity_token", :type => "hidden", :value => "yp/QcQnE9PRzexqN3LPb7drKH2IdB6YiaPFBEvlw/ljgtAacLtRrjhRvw1d3C27HPf+Q0DGqMLafQH9ZpYVopA=="}/
            %textarea#comment_body{:name => "comment[body]", :required => "required"}
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br/
            %button.commentBtn{:name => "button", :type => "submit"}
              コメントする
      %ul.links
        %li
          %i.fas.fa-chevron-left
          = link_to ("前の商品"),'#'
        %li
          = link_to ("後ろの商品"),'#'
          %i.fas.fa-chevron-right
      .relatedItems
        = link_to ("メンズをもっと見る"),'#'
        .productLis

%aside.bottum-app
  .bottum-content
    .headlines
      .headlines__title
        だれでもかんたん、人生を変えるフリマアプリ
      .headlines__text
        今すぐ無料ダウンロード！
      .content__btn
        .content__btn--appstore
          = link_to image_tag("material/logo/download-on-the-app-store-apple-2.svg", class: "appstore"), "https://apps.apple.com/jp/app/%E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB-%E3%83%AC%E3%82%B8%E3%82%A7%E3%83%B3%E3%82%BA/id1358232022"
        .content__btn--googleplay
          = link_to image_tag("material/logo/google-play-badge.svg", class: "googleplay"), "https://play.google.com/store/apps/details?id=com.bandainamcoent.dblegends_jp"

.footer
  %ul.contents
    %li.content
      .content__top
        FURIMAについて
      %ul.content__lists
        %li.content__lists--list
          = link_to "会社概要（運営会社）","#", class: "footer-link"
        %li.content__lists--list
          = link_to "プライバシーポリシー","#", class: "footer-link"
        %li.content__lists--list
          = link_to "FURIMA利用規約","#", class: "footer-link"
        %li.content__lists--list
          = link_to "ポイントに関する特約","#", class: "footer-link"
    %li.content
      .content__top
        FURIMAを見る
      %ul.content__lists
        %li.content__lists--list
          = link_to "カテゴリー一覧","#", class: "footer-link"
        %li.content__lists--list
          = link_to "ブランド一覧","#", class: "footer-link"
    %li.content
      .content__top
        ヘルプ＆ガイド
      %ul.content__lists
        %li.content__lists--list
          = link_to "FURIMAガイド","#", class: "footer-link"
        %li.content__lists--list
          = link_to "FURIMAロゴ利用ガイドライン","#", class: "footer-link"
        %li.content__lists--list
          = link_to "お知らせ","#", class: "footer-link"
  .footer__logo
    = link_to image_tag("material/logo/logo-white.png", class: "footer-logo"), "#"
  .footer__logotext
    © FURIMA
       